[workspace]
resolver = "3"
members = ["crates/repl", "crates/interpreter", "crates/expander", "crates/lsp", "crates/compiler/inkveld", "crates/veld", "crates/bytecode", "crates/common", "crates/error", "crates/veldoc"]
