[package]
name = "veld-core"
version = "0.1.3"
edition = "2024"

[dependencies]
logos = "0.13"             # For lexing
thiserror = "1.0"          # For error handling
tracing = "0.1"            # For tracing support
tracing-subscriber = "0.3" # For tracing subscriber
