name: Haskell 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache cabal packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          ~/.ghc
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Set up GHC
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.4'

    - name: Build
      run: cabal build

    - name: Run tests
      run: cabal test
